const fs = require('fs')

const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      exp: 0,
      level: 0,
      role: 'Warrior V',
      lastclaim: 0,
      lastrob: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      spam: 0,
      warning: 0,
      age: 0,
      reg_time: 0,
      registered: false,
   },
   groups: {
      activity: 0,
      mute: false,
      welcome: true,
      left: true,
      text_welcome: 'Hi @user👋\nWelcome to @subject\n\n@desc',
      text_left: 'Sayonara.... @user',
      autodetect: false,
      autosticker: false,
      antidelete: false,
      antilink: false,
      antivirtex: false,
      antisticker: false,
      antitagsw: false,
      antiporn: false,
      antibot: false,
      antiviewonce: false,
      antitoxic: false,
      autoclose: {
         active: false,
         start: null,
         end: null,
         isClosed: false
      },
      member: {},
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: false,
      anticall: true,
      self: false,
      online: true,
      antispam: true,
      debug: false,
      notifier: false,
      autodownload: false,
      groupmode: false,
      privatemode: false,
      noprefix: false,
      multiprefix: true,
      onlyprefix: '#',
      prefix: ['.', '/', '#', '!'],
      hidden: [],
      error: [],
      pluginDisable: [],
      lastReset: new Date * 1,
      sk_pack: '@nerisa',
      sk_author: 'kiznavierr',
      toxic: ['jancok', 'bajingan', 'kontol', 'memek'],
      owners: ['6283866857978'],
      msg: '+greeting +tag👋\nI am an automated bot ready to help you with small tasks, such as creating stickers, downloading media, doing homework, etc.\n\n◦  *Version* : +version\n◦  *Library* : +library\n◦  *Database* : +db\n◦  *Source* : https://github.com/Kiznaiverr/nerisa\n◦  *Rest API* : https://api.alyachan.dev\n\nIf there are any errors or bugs, please contact the owner.',
      style: 2,
      cover: fs.readFileSync(`./lib/assets/images/thumbnail.jpg`),
      link: ''
   }
}

module.exports = { models }